### ISSUE TITLE
Delete comments after everything :ok_hand:

### ISSUE THREAD

**Issue by jure** [thoughtbot/hound#390]
After fixing all issues that Hound CI found, there's a lot of leftover noise on the pull request: https://github.com/articlemetrics/alm-report/pull/40

I know that one of the functions of this is free advertisement for Hound, but it's really really noisy. Would it be possible to delete all comments if latest commit in a PR has no found issues?

**Comment by salbertson** [comment]
@sirwolfgang @jure, comments fold nicely when the style issues are fixed and pushed to the Pull Request. Are you seeing something different, or is that not enough in your opinion?

**Comment by sirwolfgang** [comment]
@salbertson are you referring to a newer behavior, I have not tried recently.

**Comment by salbertson** [comment]
@sirwolfgang, I'm referring to how GitHub hides comments nicely if there has been a change to the commented line. This works out for Hound because the comment will be hidden if the style issue is addressed.

![screenshot 2015-02-15 04 33 45](https://cloud.githubusercontent.com/assets/154463/6203250/01d07506-b4cc-11e4-8b46-bdcbac941107.png)

**Comment by zlx** [comment]
+1

**Comment by salbertson** [comment]
We don't have any plans to delete comments. We have talked about allowing users to disable comments in favor of a "report" page that is linked to from the Pull Request status, but no work has started on that.

**Comment by davidguthu** [comment]
:+1: on the reports page feature.

**Comment by darrenleeweber** [comment]
:+1: on the reports page.

**Comment by wujibear** [comment]
Is reports page an option yet? because I personally can't stand the swamp of comments that stay behind after fixing everything.

Code climate has a browser plugin that gives you feedback on what's wrong in-line without it being a comment in GH.
That's probably a fair chunk of work to accomplish something similar, but the reports page is a great move as it gives you all the details and way less noise.
