### ISSUE TITLE
Problem activating private repos for thoughtbot users 

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/hound#555]
getting an unhelpful error - will try to add something more verbose!

**Comment by mrgilman** [comment]
I'm trying to turn on Hound on a new thoughtbot private repo and am getting a 502. Is this the same issue?

**Comment by JoelQ** [comment]
I ran into this as well:
![your repos hound 2015-02-02 10-21-30](https://cloud.githubusercontent.com/assets/1006966/6002908/3dd428c4-aac5-11e4-989f-be56f1d6ffc4.jpg)

**Comment by salbertson** [comment]
Yea, I agree, the messaging is not great. I think there is an issue specific to thoughtbot repos. @gylaz, what permissions do thoughtbot org members need to enable Hound?

**Comment by gylaz** [comment]
I'm not sure exactly. thoughtbot is on a beta program for permissions. I think only admins can activate repos, because only admins can create teams under this new permissions scheme. Given that, we don't need those permissions if Hound is already added to the organization.

**Comment by thorncp** [comment]
This is definitely due to our beta permissions. The alert message was updated awhile ago to better shed light on the issue.

![your_repos___hound](https://cloud.githubusercontent.com/assets/72176/8631106/5e8ec084-2724-11e5-93a6-6b679140e30b.png)

Since no one else has commented here in the past few months, I'm guessing the message has been good enough to point people to a solution, and this issue can be closed.
