### ISSUE TITLE
indentation inside switch-case is wrong 

### ISSUE THREAD

**Issue by samirchian** [thoughtbot/hound#601]
![image](https://cloud.githubusercontent.com/assets/7979308/6007503/7d119c24-aacf-11e4-896c-bc37662b6e42.png)

**Comment by Koronen** [comment]
Hound depends on [JSHint](https://github.com/jshint/jshint) (via [jshint-rb](https://github.com/stereobooster/jshintrb)) to lint JavaScript. I'm thinking this is could be a bug in JSHint.

**Comment by Koronen** [comment]
jshintrb has not been updated since May 23 2013 and still depends on JSHint 2.1.2 (jshint/jshint@d459a40914a26c566ba82bb145e97573ff123879 to be precise). The behavior of the `indent` option [was updated in JSHint 2.5.0](https://github.com/jshint/jshint/releases/tag/2.5.0) and JSHint no longer warns about inconsistent indentation (from what I understand).

Related: #418, #438

**Comment by gylaz** [comment]
Thanks @Koronen! It seems that the creator of `jshintrb` has gone MIA. I've opened an issue a while back to take over the project, but with no response: https://github.com/stereobooster/jshintrb/issues/19

It might make sense to fork it, and to release it under a different name.

**Comment by thorncp** [comment]
Is this still an issue? We updated JSHint in 331eecde, so I'm wondering if it's occurred since then. If not, I'm assuming it won't be fixed, since this linter has been [deprecated](http://jshint.com/docs/options/#indent).

We'll likely be investigating alternate/additional JS linters soon and we can address this if it comes up again. Closing for now.
