### ISSUE TITLE
Allow users to try Hound without asking for access to all repos

### ISSUE THREAD

**Issue by salbertson** [thoughtbot/hound#701]
Would it benefit Hound users if read/write access to private repos was requested after the user had a chance to authenticate and try Hound on a public repo?

https://twitter.com/DinisCruz/status/572682201978048512

**Comment by DinisCruz** [comment]
I think this would make a massive difference, and in my case it is a deal breaker.

Question: Is there a wiki page that has a direct mapping to the 'privs requested to github' to the corresponding 'hound features'

Maybe having 'sliding scale of capabilities' which would depend on how much privs you are assigned?

**Comment by salbertson** [comment]
Here's the branch where this work is being done, https://github.com/thoughtbot/hound/tree/sa-github-scopes.

**Comment by fpietrosanti** [comment]
+1000 Let us know when it's ready, GlobaLeaks Anonymous Whistleblowing project and OpenPGP.js encryption library will immediately start using it!

**Comment by salbertson** [comment]
Related: https://github.com/thoughtbot/hound/issues/597

**Comment by fpietrosanti** [comment]
Any time estimate for delivery of that feature? :*

**Comment by thorncp** [comment]
This is now live!

**Comment by salbertson** [comment]
@thorncp spoke too soon, my bad.

**Comment by fpietrosanti** [comment]
Related to #895

**Comment by salbertson** [comment]
@fpietrosanti yea, sorry about that. Here's a [new PR](https://github.com/thoughtbot/hound/pull/900) that will hopefully be wrapped up soon.

**Comment by fpietrosanti** [comment]
@salbertson ack, will test once avilable! Super thanks! :)

**Comment by salbertson** [comment]
@fpietrosanti it's in production, again!

**Comment by salbertson** [comment]
Done. https://github.com/thoughtbot/hound/pull/900

**Comment by fpietrosanti** [comment]
@salbertson I've tried and now it ask me to authorized "organization access"  but at the same time it keep asking the WRITE privilege permission to the Code, Wiki and everything else.

At GlobaLeaks we would not be able to use it by giving to @houndci such high level of privileges.

Would you be able to make so that for Public Repository it does only ask for READ privileges but not for WRITE on the Code, Wiki and other part of the software project that does not need high privileges?

Below screenshot of the inquiry for read and write privileges to all:
<img width="784" alt="screen shot 2015-08-30 at 8 56 26 pm" src="https://cloud.githubusercontent.com/assets/770363/9568931/f122a03e-4f59-11e5-9a95-b88ab66da932.png">

**Comment by salbertson** [comment]
The other option is to ask for `repo:status` and `admin:repo_hook` instead of `public_repo`. The only potential issue is those scopes allow reading and writing of status and hooks for public and private repos.

@fpietrosanti would that approach work?

**Comment by fpietrosanti** [comment]
@salbertson Well, as long as Hound does not ask WRITE access to the repository to do it's marvelous task/service, we're definitively fine! :)

**Comment by willnorris** [comment]
+1 to repo:status scope.  I'd like to try using this for some Google projects, but granting write access to the repo is an absolutely non-starter.

**Comment by jessaustin** [comment]
@salbertson did anything ever come of this? I'm quite reluctant to grant complete write access to my public repos.
