### ISSUE TITLE
Idea: Detect TODO's and FIXME's

### ISSUE THREAD

**Issue by matthewford** [thoughtbot/hound#784]
https://github.com/pgilad/leasot

**Comment by teoljungberg** [comment]
TODO's and FIXME's are easy to spot and rarely get across code reviews. They should be fixed then and there and not be merged in and left sitting. Once they have been merged in they aren't touched until they are removed. Which doesn't really fit into Hound, since we're only commenting on lines that are changed.

Thanks for bringing up ideas @matthewford !
