### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by mjacobus** [thoughtbot/hound#956]
Hey guys

Apparently the bellow warning is a bug. I do have a blank line before and after "private".

Cheers!

![hound_warning](https://cloud.githubusercontent.com/assets/226834/10390442/f9513d0e-6e78-11e5-8204-b6068a2d903b.png)

**Comment by thorncp** [comment]
@mjacobus, looking at the [PR itself](https://github.com/mjacobus/koine-repository/pull/3), it looks like this comment was added, then [the violation was fixed](https://github.com/mjacobus/koine-repository/commit/3b3bd5a50c8769b23604d47806e8090eb19d4e28#diff-f8fbb0377cab764ba391009d13c5c4d3). The comment didn't collapse because the line it's on did not change. This is the intended behavior from GitHub.
