### ISSUE TITLE
Provide rule name in the commit message

### ISSUE THREAD

**Issue by Nowaker** [thoughtbot/hound#998]
Actual: 1 trailing blank lines detected.
Expected: 1 trailing blank lines detected. (Style/TrailingBlankLines)

This helps a lot in these situations:

1. Developer can quickly disable the rule if they don't like it. It's extremely frustrating to tune HoundCI config without knowing Rubocop. This would let developers tune HoundCI output without having to dig into Rubocop. https://twitter.com/nwkr/status/663556461855834112
1. Developer can use Rubocop auto-correct feature to fix it `bundle exec rubocop --only Style/TrailingBlankLines -a -c .hound.ruby.yml path/to/file`. (I wouldn't dare to fix all violations across all files in the repo!)

**Comment by thorncp** [comment]
This feature is configurable via the [Rubocop config file](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L36). Since Hound does not munge the violation messages from Rubocop, you can get this right now by including this in the config file that Hound is using:

```yaml
AllCops:
  DisplayCopNames: true
```

![cop_names_by_thorncp_ _pull_request__112_ _thornco_dumb-ruby](https://cloud.githubusercontent.com/assets/72176/11489757/0e35e616-9787-11e5-9ad8-afd903ce7c2b.png)

**Comment by Nowaker** [comment]
Thanks @thorncp!
